# Generated by Django 3.0.4 on 2020-04-08 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('count_posts', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(verbose_name='Date registration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=2000)),
                ('author', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('likes', models.IntegerField(default=0)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Profile')),
            ],
        ),
    ]
