# Generated by Django 3.0.4 on 2020-04-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count_favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_favorites',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
