# Generated by Django 3.0.4 on 2020-04-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_profile_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default='', max_length=500),
        ),
    ]
